[package]
name = "b_demand"
description = "On-demand calculation"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "demand.rs"

[dependencies]
b_error = { path = "../error" }

salsa = "0.13.2"
