[package]
name = "b_codegen_traits"
description = "Traits for code generation"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "codegen_traits.rs"

[dependencies]
b_deps = { path = "../deps" }
b_mir = { path = "../mir" }
