[workspace]
members = [
    "src/big_s",
    "src/error",
    "src/global_defs",
    "src/lexer",
    "src/scratch-driver",
    "src/token_tree",
    "src/tree_walker",
]

default-members = [
    "src/scratch-driver"
]
