[package]
name = "bloop"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[dependencies]
chrono = "0.4"
clap = "2.32.0"
failure = "0.1.3"
regex = "1.1.0"
pest = "2.1"
pest_derive = "2.1"
rayon = "1.0.3"
cranelift = "0.26.0"
cranelift-frontend = "0.26.0"
cranelift-reader = "0.26.0"
cranelift-faerie = "0.26.0"
cranelift-module = "0.26.0"
cranelift-simplejit = "0.26.0"
faerie = "0.6.0"
specs = "0.14.1"
specs-derive = "0.3.0"
string_cache = "0.7.0"


[build-dependencies]
lalrpop = "0.16.2"
