[package]
name = "blobc"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[dependencies]
clap = "2.29.4"
failure = "0.1.1"
regex = "0.2.1"
fst = "0.3.0"
fst-regex = "0.2.0"
pest = "1.0.6"
pest_derive = "1.0.7"
rayon = "1.0.1"

[build-dependencies]
lalrpop = "0.14.0"
