[package]
name = "bloop"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[dependencies]

# basics
chrono = "0.4.6"
failure = "0.1.3"
regex = "1.1.0"
string_cache = "0.7.0"

# command line parsing
clap = "2.32.0"
structopt = "0.2.14"

# logging
log = "0.4.6"
env_logger = "0.6.0"

# architecture
differential-dataflow = "0.8.0"
timely = "0.8.0"
rayon = "1.0.3"
specs = "0.14.1"
specs-derive = "0.3.0"

# lexing
pest = "2.1.0"
pest_derive = "2.1"

# codegen
cranelift = "0.28.0"
cranelift-frontend = "0.28.0"
cranelift-reader = "0.28.0"
cranelift-faerie = "0.28.0"
cranelift-module = "0.28.0"
cranelift-simplejit = "0.28.0"
faerie = "0.7.1"

[build-dependencies]

# parsing
lalrpop = "0.16.3"
