[workspace]
members = [
    "src/base_analyzer",
    "src/base_analyzer_traits",
    "src/base_ast",
    "src/base_parser",
    "src/base_parser_traits",
    "src/big_s",
    "src/codegen_cranelift",
    "src/codegen_traits",
    "src/error",
    "src/global_defs",
    "src/lexer",
    "src/mir",
    "src/scratch_driver",
    "src/token_tree",
    "src/tree_walker",
]

default-members = [
    "src/scratch_driver"
]
