[package]
name = "b_token_tree"
description = "Token trees - the product of bloop lexing"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "token_tree.rs"
