[package]
name = "b_ecs"
description = "The bloop entity component system"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "ecs.rs"

[dependencies]
b_error = { path = "../error" }

specs = "0.15.1"
