[package]
name = "b_mir"
description = "The bloop mid-level representation"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "mir.rs"

[dependencies]
b_base_ast = { path = "../base_ast" }
