[package]
name = "b_lang_server"
description = "Manages the compilation pipeline of a bloop workspace"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "lang_server.rs"

[dependencies]
prost = "0.5.0"
tokio = "0.2.0-alpha.6"
tonic = "0.1.0-alpha.5"
