[package]
name = "b_db_traits"
description = "Traits for bloop metadata storage"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "db_traits.rs"

[dependencies]
b_error = { path = "../error" }
