[package]
name = "b_tree_walker"
description = "Tree traversal without recursion"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "tree_walker.rs"

[dependencies]
b_error = { path = "../error" }
