[package]
name = "b_error"
description = "A simple existential error type with conversions"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0/MIT/BSL-1.0/CC0-1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "error.rs"
